const types = require('./simpleTypes');
const SpecialTypes = require('./specialTypes');
const Array = require('./array');

console.log(types.name);
console.log(types.email);
console.log(types.num);
console.log(types.age);
console.log(types.float);
console.log(types.isActive);
console.log(types.hasPermission);
console.log(types.bigNumber);
console.log(types.largeNumber);
console.log(types.uniqueValue);
console.log('=================');
console.log(SpecialTypes.value);
console.log(SpecialTypes.key);
console.log(SpecialTypes.x);
console.log(SpecialTypes.y);
console.log('=================');
console.log(Array.stringArray);
console.log(Array.numsArray);
console.log(Array.booleanArray);