const types = require('./simpleTypes');
const SpecialTypes = require('./specialTypes');
const Array = require('./array');
const ourTuple = require('./tuples');
const object = require('./object');
const enums = require('./enum');
const aliasAndInterface = require('./aliasesAndInterface');
const union = require('./union');
const functionType = require('./function');
const casting = require('./casting');
const classes = require('./class');
const generics = require('./generic');
const utilityTypes = require('./utilityTypes');

console.log(types.name);
console.log(types.email);
console.log(types.num);
console.log(types.age);
console.log(types.float);
console.log(types.isActive);
console.log(types.hasPermission);
console.log(types.bigNumber);
console.log(types.largeNumber);
console.log(types.uniqueValue);
console.log('=================');
console.log(SpecialTypes.value);
console.log(SpecialTypes.key);
console.log(SpecialTypes.x);
console.log(SpecialTypes.y);
console.log('=================');
console.log(Array.stringArray);
console.log(Array.numsArray);
console.log(Array.booleanArray);
console.log('=================');
console.log(ourTuple);
console.log('=================');
console.log(object.car);
console.log(object.student);
console.log(object.productStok);
console.log('=================');
console.log(enums.Diraction);
console.log(enums.move);
console.log(enums.Rules);
console.log(enums.role);
console.log(enums.Mixed);
console.log(enums.PaymentMethod);
console.log(enums.pay);
console.log('=================');
console.log(aliasAndInterface.userId);
console.log(aliasAndInterface.user1);
console.log(aliasAndInterface.scores);
console.log(aliasAndInterface.student);
console.log(aliasAndInterface.enginer1);
console.log(aliasAndInterface.doctor1);
console.log('=================');
console.log(union.id);
console.log(union.printId);
console.log(union.data);
console.log('=================');
console.log(functionType.add);
console.log(functionType.printHello);
console.log(functionType.sum);
console.log('=================');
console.log(casting.stringLength);
console.log(casting.helloLength);
console.log('=================');
console.log(classes.p1);
console.log(classes.u1);
console.log(classes.d1);
console.log(classes.sh);
console.log(classes.an1);
console.log(classes.dog1);
console.log('=================');
console.log(generics.idint1);
console.log(generics.idint2);
console.log(generics.key);
console.log(generics.stringBox);
console.log(generics.numberBox);
console.log(generics.arrayStingBox);
console.log(generics.res);
console.log('=================');
console.log(utilityTypes.userOptional);
console.log(utilityTypes.userRequired);
console.log(utilityTypes.userName);
console.log(utilityTypes.ageAndEmailUser);
console.log(utilityTypes.car);
console.log('=================');